---
title: Picpic现场互动 - 博客
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: "© Heluofan Technology Inc."
email: service@picpic.live
home_url: https://picpiclive.com
home_title: 主页
blog_home_title: 博客主页
logourl: https://drcn65av4x1ah.cloudfront.net/favicon-270x270.png
description: Picpic现场互动 - 博客
baseurl: "/blog"
url: https://picpiclive.com
twitter_username: picpiclive
instagram_username: picpic_live
facebook_username: Picpic-Live-161583901330530
facebook_displayname: Picpic Live
youtube_username: UCShZ-r3w5xyvdxpmmBBfh6w
youtube_displayname: Picpic Live
default_list_title: 全部文章
markdown: kramdown
theme: minima
live_interactions_url: "/products/live-interactions/"
sponsorship_url: "/products/sponsorship/"
demo_url: "/demo/"
plugins:
- jekyll-feed
- jekyll-admin
prose:
  media: uploads
